@echo off
echo [后端] 检查Python虚拟环境...
if exist "venv\Scripts\activate.bat" (
    echo [后端] 激活虚拟环境...
    call venv\Scripts\activate.bat
) else (
    echo [后端] 未找到虚拟环境，使用系统Python...
)

echo [后端] 检查依赖包...
python -c "import uvicorn" >nul 2>&1
if %errorlevel% neq 0 (
    echo [后端] 正在安装依赖...
    pip install -r requirements.txt
)

echo [后端] 启动 Uvicorn 服务器...
uvicorn api.main:app --reload --port 8000 --host 0.0.0.0
